// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fypzyvofiqbkirgmiwyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5cHp5dm9maXFia2lyZ21pd3lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTM0MTYsImV4cCI6MjA2ODI2OTQxNn0.FjQIgqdpq7eHIVuxXihNuCGCZENZ4KgUGWAugpMaCDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});